<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYNHANSU_6" Class="DBQLNhanSu_6DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-LCSFN5D\MSSQLSERVER01;Initial Catalog=QUANLYNHANSU_6;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="QUANLYNHANSU_6ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHUCVU6" Member="CHUCVU6s">
    <Type Name="CHUCVU6">
      <Column Name="MACV" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCV" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="HESOPC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CHUCVU6_NHANVIEN_CHUCVU6" Member="NHANVIEN_CHUCVU6s" ThisKey="MACV" OtherKey="MACV" Type="NHANVIEN_CHUCVU6" />
    </Type>
  </Table>
  <Table Name="dbo.HOSO6" Member="HOSO6s">
    <Type Name="HOSO6">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SODT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYTD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MAPB" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TAIKHOAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="QUYEN" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="HOSO6_NHANVIEN_CHUCVU6" Member="NHANVIEN_CHUCVU6s" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN_CHUCVU6" />
      <Association Name="HOSO6_QUATRINHCONGTAC6" Member="QUATRINHCONGTAC6s" ThisKey="MANV" OtherKey="MANV" Type="QUATRINHCONGTAC6" />
      <Association Name="HOSO6_TRINHDOCHUYENMON6" Member="TRINHDOCHUYENMON6s" ThisKey="MANV" OtherKey="MANV" Type="TRINHDOCHUYENMON6" />
      <Association Name="HOSO6_TRINHDONGOAINGU6" Member="TRINHDONGOAINGU6s" ThisKey="MANV" OtherKey="MANV" Type="TRINHDONGOAINGU6" />
      <Association Name="PHONGBAN6_HOSO6" Member="PHONGBAN6" ThisKey="MAPB" OtherKey="MAPB" Type="PHONGBAN6" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN_CHUCVU6" Member="NHANVIEN_CHUCVU6s">
    <Type Name="NHANVIEN_CHUCVU6">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MACV" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TUNGAY" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DENNGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="CHUCVU6_NHANVIEN_CHUCVU6" Member="CHUCVU6" ThisKey="MACV" OtherKey="MACV" Type="CHUCVU6" IsForeignKey="true" />
      <Association Name="HOSO6_NHANVIEN_CHUCVU6" Member="HOSO6" ThisKey="MANV" OtherKey="MANV" Type="HOSO6" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGBAN6" Member="PHONGBAN6s">
    <Type Name="PHONGBAN6">
      <Column Name="MAPB" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPB" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYTL" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PHONGBAN6_HOSO6" Member="HOSO6s" ThisKey="MAPB" OtherKey="MAPB" Type="HOSO6" />
    </Type>
  </Table>
  <Table Name="dbo.QUATRINHCONGTAC6" Member="QUATRINHCONGTAC6s">
    <Type Name="QUATRINHCONGTAC6">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TUNGAY" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DENNGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NOICONGTAC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="HOSO6_QUATRINHCONGTAC6" Member="HOSO6" ThisKey="MANV" OtherKey="MANV" Type="HOSO6" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRINHDOCHUYENMON6" Member="TRINHDOCHUYENMON6s">
    <Type Name="TRINHDOCHUYENMON6">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGANH" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TRINHDO" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LOAIHINHDT" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TRUONGDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HOSO6_TRINHDOCHUYENMON6" Member="HOSO6" ThisKey="MANV" OtherKey="MANV" Type="HOSO6" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRINHDONGOAINGU6" Member="TRINHDONGOAINGU6s">
    <Type Name="TRINHDONGOAINGU6">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGOAINGU" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TRINHDO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="HOSO6_TRINHDONGOAINGU6" Member="HOSO6" ThisKey="MANV" OtherKey="MANV" Type="HOSO6" IsForeignKey="true" />
    </Type>
  </Table>
</Database>