#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_Nhom6
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYNHANSU_6")]
	public partial class DBQLNhanSu_6DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTRINHDONGOAINGU6(TRINHDONGOAINGU6 instance);
    partial void UpdateTRINHDONGOAINGU6(TRINHDONGOAINGU6 instance);
    partial void DeleteTRINHDONGOAINGU6(TRINHDONGOAINGU6 instance);
    partial void InsertTRINHDOCHUYENMON6(TRINHDOCHUYENMON6 instance);
    partial void UpdateTRINHDOCHUYENMON6(TRINHDOCHUYENMON6 instance);
    partial void DeleteTRINHDOCHUYENMON6(TRINHDOCHUYENMON6 instance);
    partial void InsertQUATRINHCONGTAC6(QUATRINHCONGTAC6 instance);
    partial void UpdateQUATRINHCONGTAC6(QUATRINHCONGTAC6 instance);
    partial void DeleteQUATRINHCONGTAC6(QUATRINHCONGTAC6 instance);
    partial void InsertPHONGBAN6(PHONGBAN6 instance);
    partial void UpdatePHONGBAN6(PHONGBAN6 instance);
    partial void DeletePHONGBAN6(PHONGBAN6 instance);
    partial void InsertHOSO6(HOSO6 instance);
    partial void UpdateHOSO6(HOSO6 instance);
    partial void DeleteHOSO6(HOSO6 instance);
    partial void InsertNHANVIEN_CHUCVU6(NHANVIEN_CHUCVU6 instance);
    partial void UpdateNHANVIEN_CHUCVU6(NHANVIEN_CHUCVU6 instance);
    partial void DeleteNHANVIEN_CHUCVU6(NHANVIEN_CHUCVU6 instance);
    partial void InsertCHUCVU6(CHUCVU6 instance);
    partial void UpdateCHUCVU6(CHUCVU6 instance);
    partial void DeleteCHUCVU6(CHUCVU6 instance);
    #endregion
		
		public DBQLNhanSu_6DataContext() : 
				base(global::QuanLyNhanSu_Nhom6.Properties.Settings.Default.QUANLYNHANSU_6ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBQLNhanSu_6DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQLNhanSu_6DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQLNhanSu_6DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQLNhanSu_6DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TRINHDONGOAINGU6> TRINHDONGOAINGU6s
		{
			get
			{
				return this.GetTable<TRINHDONGOAINGU6>();
			}
		}
		
		public System.Data.Linq.Table<TRINHDOCHUYENMON6> TRINHDOCHUYENMON6s
		{
			get
			{
				return this.GetTable<TRINHDOCHUYENMON6>();
			}
		}
		
		public System.Data.Linq.Table<QUATRINHCONGTAC6> QUATRINHCONGTAC6s
		{
			get
			{
				return this.GetTable<QUATRINHCONGTAC6>();
			}
		}
		
		public System.Data.Linq.Table<PHONGBAN6> PHONGBAN6s
		{
			get
			{
				return this.GetTable<PHONGBAN6>();
			}
		}
		
		public System.Data.Linq.Table<HOSO6> HOSO6s
		{
			get
			{
				return this.GetTable<HOSO6>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN_CHUCVU6> NHANVIEN_CHUCVU6s
		{
			get
			{
				return this.GetTable<NHANVIEN_CHUCVU6>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU6> CHUCVU6s
		{
			get
			{
				return this.GetTable<CHUCVU6>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRINHDONGOAINGU6")]
	public partial class TRINHDONGOAINGU6 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _NGOAINGU;
		
		private string _TRINHDO;
		
		private EntityRef<HOSO6> _HOSO6;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGOAINGUChanging(string value);
    partial void OnNGOAINGUChanged();
    partial void OnTRINHDOChanging(string value);
    partial void OnTRINHDOChanged();
    #endregion
		
		public TRINHDONGOAINGU6()
		{
			this._HOSO6 = default(EntityRef<HOSO6>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._HOSO6.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGOAINGU", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NGOAINGU
		{
			get
			{
				return this._NGOAINGU;
			}
			set
			{
				if ((this._NGOAINGU != value))
				{
					this.OnNGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._NGOAINGU = value;
					this.SendPropertyChanged("NGOAINGU");
					this.OnNGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDO", DbType="NVarChar(20)")]
		public string TRINHDO
		{
			get
			{
				return this._TRINHDO;
			}
			set
			{
				if ((this._TRINHDO != value))
				{
					this.OnTRINHDOChanging(value);
					this.SendPropertyChanging();
					this._TRINHDO = value;
					this.SendPropertyChanged("TRINHDO");
					this.OnTRINHDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO6_TRINHDONGOAINGU6", Storage="_HOSO6", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public HOSO6 HOSO6
		{
			get
			{
				return this._HOSO6.Entity;
			}
			set
			{
				HOSO6 previousValue = this._HOSO6.Entity;
				if (((previousValue != value) 
							|| (this._HOSO6.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOSO6.Entity = null;
						previousValue.TRINHDONGOAINGU6s.Remove(this);
					}
					this._HOSO6.Entity = value;
					if ((value != null))
					{
						value.TRINHDONGOAINGU6s.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("HOSO6");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRINHDOCHUYENMON6")]
	public partial class TRINHDOCHUYENMON6 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _NGANH;
		
		private string _TRINHDO;
		
		private string _LOAIHINHDT;
		
		private string _TRUONGDT;
		
		private EntityRef<HOSO6> _HOSO6;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGANHChanging(string value);
    partial void OnNGANHChanged();
    partial void OnTRINHDOChanging(string value);
    partial void OnTRINHDOChanged();
    partial void OnLOAIHINHDTChanging(string value);
    partial void OnLOAIHINHDTChanged();
    partial void OnTRUONGDTChanging(string value);
    partial void OnTRUONGDTChanged();
    #endregion
		
		public TRINHDOCHUYENMON6()
		{
			this._HOSO6 = default(EntityRef<HOSO6>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._HOSO6.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGANH", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NGANH
		{
			get
			{
				return this._NGANH;
			}
			set
			{
				if ((this._NGANH != value))
				{
					this.OnNGANHChanging(value);
					this.SendPropertyChanging();
					this._NGANH = value;
					this.SendPropertyChanged("NGANH");
					this.OnNGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDO", DbType="NVarChar(30)")]
		public string TRINHDO
		{
			get
			{
				return this._TRINHDO;
			}
			set
			{
				if ((this._TRINHDO != value))
				{
					this.OnTRINHDOChanging(value);
					this.SendPropertyChanging();
					this._TRINHDO = value;
					this.SendPropertyChanged("TRINHDO");
					this.OnTRINHDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIHINHDT", DbType="NVarChar(30)")]
		public string LOAIHINHDT
		{
			get
			{
				return this._LOAIHINHDT;
			}
			set
			{
				if ((this._LOAIHINHDT != value))
				{
					this.OnLOAIHINHDTChanging(value);
					this.SendPropertyChanging();
					this._LOAIHINHDT = value;
					this.SendPropertyChanged("LOAIHINHDT");
					this.OnLOAIHINHDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRUONGDT", DbType="NVarChar(50)")]
		public string TRUONGDT
		{
			get
			{
				return this._TRUONGDT;
			}
			set
			{
				if ((this._TRUONGDT != value))
				{
					this.OnTRUONGDTChanging(value);
					this.SendPropertyChanging();
					this._TRUONGDT = value;
					this.SendPropertyChanged("TRUONGDT");
					this.OnTRUONGDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO6_TRINHDOCHUYENMON6", Storage="_HOSO6", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public HOSO6 HOSO6
		{
			get
			{
				return this._HOSO6.Entity;
			}
			set
			{
				HOSO6 previousValue = this._HOSO6.Entity;
				if (((previousValue != value) 
							|| (this._HOSO6.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOSO6.Entity = null;
						previousValue.TRINHDOCHUYENMON6s.Remove(this);
					}
					this._HOSO6.Entity = value;
					if ((value != null))
					{
						value.TRINHDOCHUYENMON6s.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("HOSO6");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUATRINHCONGTAC6")]
	public partial class QUATRINHCONGTAC6 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private System.DateTime _TUNGAY;
		
		private System.Nullable<System.DateTime> _DENNGAY;
		
		private string _NOICONGTAC;
		
		private string _CHUCVU;
		
		private EntityRef<HOSO6> _HOSO6;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTUNGAYChanging(System.DateTime value);
    partial void OnTUNGAYChanged();
    partial void OnDENNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnDENNGAYChanged();
    partial void OnNOICONGTACChanging(string value);
    partial void OnNOICONGTACChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    #endregion
		
		public QUATRINHCONGTAC6()
		{
			this._HOSO6 = default(EntityRef<HOSO6>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._HOSO6.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUNGAY", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime TUNGAY
		{
			get
			{
				return this._TUNGAY;
			}
			set
			{
				if ((this._TUNGAY != value))
				{
					this.OnTUNGAYChanging(value);
					this.SendPropertyChanging();
					this._TUNGAY = value;
					this.SendPropertyChanged("TUNGAY");
					this.OnTUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENNGAY", DbType="Date")]
		public System.Nullable<System.DateTime> DENNGAY
		{
			get
			{
				return this._DENNGAY;
			}
			set
			{
				if ((this._DENNGAY != value))
				{
					this.OnDENNGAYChanging(value);
					this.SendPropertyChanging();
					this._DENNGAY = value;
					this.SendPropertyChanged("DENNGAY");
					this.OnDENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOICONGTAC", DbType="NVarChar(50)")]
		public string NOICONGTAC
		{
			get
			{
				return this._NOICONGTAC;
			}
			set
			{
				if ((this._NOICONGTAC != value))
				{
					this.OnNOICONGTACChanging(value);
					this.SendPropertyChanging();
					this._NOICONGTAC = value;
					this.SendPropertyChanged("NOICONGTAC");
					this.OnNOICONGTACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(20)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO6_QUATRINHCONGTAC6", Storage="_HOSO6", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public HOSO6 HOSO6
		{
			get
			{
				return this._HOSO6.Entity;
			}
			set
			{
				HOSO6 previousValue = this._HOSO6.Entity;
				if (((previousValue != value) 
							|| (this._HOSO6.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOSO6.Entity = null;
						previousValue.QUATRINHCONGTAC6s.Remove(this);
					}
					this._HOSO6.Entity = value;
					if ((value != null))
					{
						value.QUATRINHCONGTAC6s.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("HOSO6");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGBAN6")]
	public partial class PHONGBAN6 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPB;
		
		private string _TENPB;
		
		private System.Nullable<System.DateTime> _NGAYTL;
		
		private EntitySet<HOSO6> _HOSO6s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPBChanging(string value);
    partial void OnMAPBChanged();
    partial void OnTENPBChanging(string value);
    partial void OnTENPBChanged();
    partial void OnNGAYTLChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTLChanged();
    #endregion
		
		public PHONGBAN6()
		{
			this._HOSO6s = new EntitySet<HOSO6>(new Action<HOSO6>(this.attach_HOSO6s), new Action<HOSO6>(this.detach_HOSO6s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPB", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPB
		{
			get
			{
				return this._MAPB;
			}
			set
			{
				if ((this._MAPB != value))
				{
					this.OnMAPBChanging(value);
					this.SendPropertyChanging();
					this._MAPB = value;
					this.SendPropertyChanged("MAPB");
					this.OnMAPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPB", DbType="NVarChar(30)")]
		public string TENPB
		{
			get
			{
				return this._TENPB;
			}
			set
			{
				if ((this._TENPB != value))
				{
					this.OnTENPBChanging(value);
					this.SendPropertyChanging();
					this._TENPB = value;
					this.SendPropertyChanged("TENPB");
					this.OnTENPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTL", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTL
		{
			get
			{
				return this._NGAYTL;
			}
			set
			{
				if ((this._NGAYTL != value))
				{
					this.OnNGAYTLChanging(value);
					this.SendPropertyChanging();
					this._NGAYTL = value;
					this.SendPropertyChanged("NGAYTL");
					this.OnNGAYTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGBAN6_HOSO6", Storage="_HOSO6s", ThisKey="MAPB", OtherKey="MAPB")]
		public EntitySet<HOSO6> HOSO6s
		{
			get
			{
				return this._HOSO6s;
			}
			set
			{
				this._HOSO6s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOSO6s(HOSO6 entity)
		{
			this.SendPropertyChanging();
			entity.PHONGBAN6 = this;
		}
		
		private void detach_HOSO6s(HOSO6 entity)
		{
			this.SendPropertyChanging();
			entity.PHONGBAN6 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOSO6")]
	public partial class HOSO6 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _SODT;
		
		private string _EMAIL;
		
		private System.Nullable<System.DateTime> _NGAYTD;
		
		private string _MAPB;
		
		private string _TAIKHOAN;
		
		private string _MATKHAU;
		
		private string _QUYEN;
		
		private EntitySet<TRINHDONGOAINGU6> _TRINHDONGOAINGU6s;
		
		private EntitySet<TRINHDOCHUYENMON6> _TRINHDOCHUYENMON6s;
		
		private EntitySet<QUATRINHCONGTAC6> _QUATRINHCONGTAC6s;
		
		private EntitySet<NHANVIEN_CHUCVU6> _NHANVIEN_CHUCVU6s;
		
		private EntityRef<PHONGBAN6> _PHONGBAN6;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSODTChanging(string value);
    partial void OnSODTChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNGAYTDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTDChanged();
    partial void OnMAPBChanging(string value);
    partial void OnMAPBChanged();
    partial void OnTAIKHOANChanging(string value);
    partial void OnTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnQUYENChanging(string value);
    partial void OnQUYENChanged();
    #endregion
		
		public HOSO6()
		{
			this._TRINHDONGOAINGU6s = new EntitySet<TRINHDONGOAINGU6>(new Action<TRINHDONGOAINGU6>(this.attach_TRINHDONGOAINGU6s), new Action<TRINHDONGOAINGU6>(this.detach_TRINHDONGOAINGU6s));
			this._TRINHDOCHUYENMON6s = new EntitySet<TRINHDOCHUYENMON6>(new Action<TRINHDOCHUYENMON6>(this.attach_TRINHDOCHUYENMON6s), new Action<TRINHDOCHUYENMON6>(this.detach_TRINHDOCHUYENMON6s));
			this._QUATRINHCONGTAC6s = new EntitySet<QUATRINHCONGTAC6>(new Action<QUATRINHCONGTAC6>(this.attach_QUATRINHCONGTAC6s), new Action<QUATRINHCONGTAC6>(this.detach_QUATRINHCONGTAC6s));
			this._NHANVIEN_CHUCVU6s = new EntitySet<NHANVIEN_CHUCVU6>(new Action<NHANVIEN_CHUCVU6>(this.attach_NHANVIEN_CHUCVU6s), new Action<NHANVIEN_CHUCVU6>(this.detach_NHANVIEN_CHUCVU6s));
			this._PHONGBAN6 = default(EntityRef<PHONGBAN6>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODT", DbType="NVarChar(15)")]
		public string SODT
		{
			get
			{
				return this._SODT;
			}
			set
			{
				if ((this._SODT != value))
				{
					this.OnSODTChanging(value);
					this.SendPropertyChanging();
					this._SODT = value;
					this.SendPropertyChanged("SODT");
					this.OnSODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTD
		{
			get
			{
				return this._NGAYTD;
			}
			set
			{
				if ((this._NGAYTD != value))
				{
					this.OnNGAYTDChanging(value);
					this.SendPropertyChanging();
					this._NGAYTD = value;
					this.SendPropertyChanged("NGAYTD");
					this.OnNGAYTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPB", DbType="NVarChar(20)")]
		public string MAPB
		{
			get
			{
				return this._MAPB;
			}
			set
			{
				if ((this._MAPB != value))
				{
					if (this._PHONGBAN6.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPBChanging(value);
					this.SendPropertyChanging();
					this._MAPB = value;
					this.SendPropertyChanged("MAPB");
					this.OnMAPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN", DbType="NVarChar(20)")]
		public string TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN;
			}
			set
			{
				if ((this._TAIKHOAN != value))
				{
					this.OnTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN = value;
					this.SendPropertyChanged("TAIKHOAN");
					this.OnTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(20)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="NVarChar(10)")]
		public string QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO6_TRINHDONGOAINGU6", Storage="_TRINHDONGOAINGU6s", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TRINHDONGOAINGU6> TRINHDONGOAINGU6s
		{
			get
			{
				return this._TRINHDONGOAINGU6s;
			}
			set
			{
				this._TRINHDONGOAINGU6s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO6_TRINHDOCHUYENMON6", Storage="_TRINHDOCHUYENMON6s", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TRINHDOCHUYENMON6> TRINHDOCHUYENMON6s
		{
			get
			{
				return this._TRINHDOCHUYENMON6s;
			}
			set
			{
				this._TRINHDOCHUYENMON6s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO6_QUATRINHCONGTAC6", Storage="_QUATRINHCONGTAC6s", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<QUATRINHCONGTAC6> QUATRINHCONGTAC6s
		{
			get
			{
				return this._QUATRINHCONGTAC6s;
			}
			set
			{
				this._QUATRINHCONGTAC6s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO6_NHANVIEN_CHUCVU6", Storage="_NHANVIEN_CHUCVU6s", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<NHANVIEN_CHUCVU6> NHANVIEN_CHUCVU6s
		{
			get
			{
				return this._NHANVIEN_CHUCVU6s;
			}
			set
			{
				this._NHANVIEN_CHUCVU6s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGBAN6_HOSO6", Storage="_PHONGBAN6", ThisKey="MAPB", OtherKey="MAPB", IsForeignKey=true)]
		public PHONGBAN6 PHONGBAN6
		{
			get
			{
				return this._PHONGBAN6.Entity;
			}
			set
			{
				PHONGBAN6 previousValue = this._PHONGBAN6.Entity;
				if (((previousValue != value) 
							|| (this._PHONGBAN6.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGBAN6.Entity = null;
						previousValue.HOSO6s.Remove(this);
					}
					this._PHONGBAN6.Entity = value;
					if ((value != null))
					{
						value.HOSO6s.Add(this);
						this._MAPB = value.MAPB;
					}
					else
					{
						this._MAPB = default(string);
					}
					this.SendPropertyChanged("PHONGBAN6");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRINHDONGOAINGU6s(TRINHDONGOAINGU6 entity)
		{
			this.SendPropertyChanging();
			entity.HOSO6 = this;
		}
		
		private void detach_TRINHDONGOAINGU6s(TRINHDONGOAINGU6 entity)
		{
			this.SendPropertyChanging();
			entity.HOSO6 = null;
		}
		
		private void attach_TRINHDOCHUYENMON6s(TRINHDOCHUYENMON6 entity)
		{
			this.SendPropertyChanging();
			entity.HOSO6 = this;
		}
		
		private void detach_TRINHDOCHUYENMON6s(TRINHDOCHUYENMON6 entity)
		{
			this.SendPropertyChanging();
			entity.HOSO6 = null;
		}
		
		private void attach_QUATRINHCONGTAC6s(QUATRINHCONGTAC6 entity)
		{
			this.SendPropertyChanging();
			entity.HOSO6 = this;
		}
		
		private void detach_QUATRINHCONGTAC6s(QUATRINHCONGTAC6 entity)
		{
			this.SendPropertyChanging();
			entity.HOSO6 = null;
		}
		
		private void attach_NHANVIEN_CHUCVU6s(NHANVIEN_CHUCVU6 entity)
		{
			this.SendPropertyChanging();
			entity.HOSO6 = this;
		}
		
		private void detach_NHANVIEN_CHUCVU6s(NHANVIEN_CHUCVU6 entity)
		{
			this.SendPropertyChanging();
			entity.HOSO6 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN_CHUCVU6")]
	public partial class NHANVIEN_CHUCVU6 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _MACV;
		
		private System.DateTime _TUNGAY;
		
		private System.Nullable<System.DateTime> _DENNGAY;
		
		private EntityRef<HOSO6> _HOSO6;
		
		private EntityRef<CHUCVU6> _CHUCVU6;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMACVChanging(string value);
    partial void OnMACVChanged();
    partial void OnTUNGAYChanging(System.DateTime value);
    partial void OnTUNGAYChanged();
    partial void OnDENNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnDENNGAYChanged();
    #endregion
		
		public NHANVIEN_CHUCVU6()
		{
			this._HOSO6 = default(EntityRef<HOSO6>);
			this._CHUCVU6 = default(EntityRef<CHUCVU6>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._HOSO6.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACV
		{
			get
			{
				return this._MACV;
			}
			set
			{
				if ((this._MACV != value))
				{
					if (this._CHUCVU6.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACVChanging(value);
					this.SendPropertyChanging();
					this._MACV = value;
					this.SendPropertyChanged("MACV");
					this.OnMACVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUNGAY", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime TUNGAY
		{
			get
			{
				return this._TUNGAY;
			}
			set
			{
				if ((this._TUNGAY != value))
				{
					this.OnTUNGAYChanging(value);
					this.SendPropertyChanging();
					this._TUNGAY = value;
					this.SendPropertyChanged("TUNGAY");
					this.OnTUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENNGAY", DbType="Date")]
		public System.Nullable<System.DateTime> DENNGAY
		{
			get
			{
				return this._DENNGAY;
			}
			set
			{
				if ((this._DENNGAY != value))
				{
					this.OnDENNGAYChanging(value);
					this.SendPropertyChanging();
					this._DENNGAY = value;
					this.SendPropertyChanged("DENNGAY");
					this.OnDENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSO6_NHANVIEN_CHUCVU6", Storage="_HOSO6", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public HOSO6 HOSO6
		{
			get
			{
				return this._HOSO6.Entity;
			}
			set
			{
				HOSO6 previousValue = this._HOSO6.Entity;
				if (((previousValue != value) 
							|| (this._HOSO6.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOSO6.Entity = null;
						previousValue.NHANVIEN_CHUCVU6s.Remove(this);
					}
					this._HOSO6.Entity = value;
					if ((value != null))
					{
						value.NHANVIEN_CHUCVU6s.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("HOSO6");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU6_NHANVIEN_CHUCVU6", Storage="_CHUCVU6", ThisKey="MACV", OtherKey="MACV", IsForeignKey=true)]
		public CHUCVU6 CHUCVU6
		{
			get
			{
				return this._CHUCVU6.Entity;
			}
			set
			{
				CHUCVU6 previousValue = this._CHUCVU6.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU6.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU6.Entity = null;
						previousValue.NHANVIEN_CHUCVU6s.Remove(this);
					}
					this._CHUCVU6.Entity = value;
					if ((value != null))
					{
						value.NHANVIEN_CHUCVU6s.Add(this);
						this._MACV = value.MACV;
					}
					else
					{
						this._MACV = default(string);
					}
					this.SendPropertyChanged("CHUCVU6");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU6")]
	public partial class CHUCVU6 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACV;
		
		private string _TENCV;
		
		private System.Nullable<double> _HESOPC;
		
		private EntitySet<NHANVIEN_CHUCVU6> _NHANVIEN_CHUCVU6s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACVChanging(string value);
    partial void OnMACVChanged();
    partial void OnTENCVChanging(string value);
    partial void OnTENCVChanged();
    partial void OnHESOPCChanging(System.Nullable<double> value);
    partial void OnHESOPCChanged();
    #endregion
		
		public CHUCVU6()
		{
			this._NHANVIEN_CHUCVU6s = new EntitySet<NHANVIEN_CHUCVU6>(new Action<NHANVIEN_CHUCVU6>(this.attach_NHANVIEN_CHUCVU6s), new Action<NHANVIEN_CHUCVU6>(this.detach_NHANVIEN_CHUCVU6s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACV
		{
			get
			{
				return this._MACV;
			}
			set
			{
				if ((this._MACV != value))
				{
					this.OnMACVChanging(value);
					this.SendPropertyChanging();
					this._MACV = value;
					this.SendPropertyChanged("MACV");
					this.OnMACVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCV", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TENCV
		{
			get
			{
				return this._TENCV;
			}
			set
			{
				if ((this._TENCV != value))
				{
					this.OnTENCVChanging(value);
					this.SendPropertyChanging();
					this._TENCV = value;
					this.SendPropertyChanged("TENCV");
					this.OnTENCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESOPC", DbType="Float")]
		public System.Nullable<double> HESOPC
		{
			get
			{
				return this._HESOPC;
			}
			set
			{
				if ((this._HESOPC != value))
				{
					this.OnHESOPCChanging(value);
					this.SendPropertyChanging();
					this._HESOPC = value;
					this.SendPropertyChanged("HESOPC");
					this.OnHESOPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU6_NHANVIEN_CHUCVU6", Storage="_NHANVIEN_CHUCVU6s", ThisKey="MACV", OtherKey="MACV")]
		public EntitySet<NHANVIEN_CHUCVU6> NHANVIEN_CHUCVU6s
		{
			get
			{
				return this._NHANVIEN_CHUCVU6s;
			}
			set
			{
				this._NHANVIEN_CHUCVU6s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIEN_CHUCVU6s(NHANVIEN_CHUCVU6 entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU6 = this;
		}
		
		private void detach_NHANVIEN_CHUCVU6s(NHANVIEN_CHUCVU6 entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU6 = null;
		}
	}
}
#pragma warning restore 1591
